spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  sql:
    init:
      mode: always
      schema-locations: classpath:sql/schema.sql

springdoc:
  version: 1.0.0
  swagger-ui:
    operations-sorter: alpha
    tags-sorter: alpha
    path: /swagger
  api-docs:
    path: /swagger/json
    groups:
      enabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  packages-to-scan: com.wantedbackendassignment.api
  show-login-endpoint: true
  cache:
    disabled: true

jwt:
  algorithm: HS256
  secret: ${JWT_SECRET}
  validity-period: 2         # 2 hours

logging:
  level:
    org:
      hibernate:
        sql: trace
        type.descriptor.sql: trace
