CREATE TABLE IF NOT EXISTS USER (
        ID                  BIGINT          AUTO_INCREMENT PRIMARY KEY,
        EMAIL               VARCHAR(255)    NOT NULL,
        PASSWORD            VARCHAR(255)    NOT NULL,
        CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS POST (
        ID                  BIGINT          AUTO_INCREMENT PRIMARY KEY,
        TITLE               VARCHAR(350)    NOT NULL,
        DESCRIPTION         VARCHAR(1600)   NOT NULL,
        AUTHOR_ID           BIGINT          NOT NULL,
        CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

        FOREIGN KEY (AUTHOR_ID) REFERENCES USER (ID) ON DELETE CASCADE
);
