CREATE TABLE IF NOT EXISTS USER (
        ID                  BIGINT          AUTO_INCREMENT PRIMARY KEY,
        EMAIL               VARCHAR(255)    NOT NULL,
        PASSWORD            VARCHAR(255)    NOT NULL,
        CREATED_DATE        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        LAST_MODIFIED_DATE  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
